### ISSUE TITLE
Create a governance proposal template

### ISSUE THREAD

**Issue by shahankhatch** [cosmos/gaia#1039]
- [ ] authors
- [ ] current status
- [ ] created date
- [ ] last modified date
- [ ] json
- [ ] link to on-chain proposal/tx (after submission)
- [ ] summary
- [ ] detailed description

**Comment by dcwalk** [comment]
Went back through the old proposals and reviewed the ADR to do some [drafting on this](https://hackmd.io/o43GADRaR-qx4Jrwqkj9pw?both), have a WIP PR with this template and more for when governance proposals are edited on github: https://github.com/cosmos/gaia/pull/1050

From above sections: 
- [x] authors
- [x] current status
- [x] created date => changelog
- [x] last modified date => changelog
- [ ] json
- [ ] link to on-chain proposal/tx (after submission)
- [x] summary (renamed proposal)
- [x] detailed description (renamed context) 

added:
- governance votes
- conclusion
- references

Created a json template in parallel + thought of leaving off the link to on-chain proposal because that would add an additional step on a new platform (github) during the "proposal" stage (which is currently just use the cli to submit): https://hub.cosmos.network/main/governance/best_practices.html and https://hub.cosmos.network/main/governance/submitting.html are relevant places this is documented The current flow is a little cumbersome anyway so thought I'd leave off adding that section for now, imagining as we improve the process we can amend the template if needed
