### ISSUE TITLE
Disk IO cost of block creation

### ISSUE THREAD

**Issue by mdyring** [cosmos/gaia#113]
In the same spirit as #111, though not really a bug and more of a question: what is the IO and storage cost of creating block?

In the case of no-empty-block config, even though it is supposed to reduce block count it might actually increase it in cases where txs arrive at sub-block-creation intervals (had block time been specified).

Everybody loves a chat log, so here goes:
```
Zaki
22:14
So I am expecting Ethereum workloads, pegzone, photon zone, ethermint zones to probably require all validators to be running raid1 SSDs if we want to mazimize network tx throughput

mdyring
hopefully some if it is trivially fixable (ref. github issue on io), at least I hope some effort will be made to reduce IO requirements it as much as possible... for sentry-protected validators (who might run, say 4-8ish) sentries, it will add up

Zaki
I think the comos io issue is fixable
So we are running the non-empty blocks testnet that we tried this morning
and the io is way down

mdyring
cool. one thing that occured to me earlier today.. even with no-empty-blocks, the number of blocks in aggregate might be larger than blocks at fixed interval.. because a single tx will trigger  a new block, right?

Zaki
yeah

mdyring
so block creation should be cheap, IO wise.. imagine a dex with no-empty-blocks
orders coming sporadically., but less than 1 sec apart. block # would grow quicker than 1 sec fixed block

Zaki
melekes: Thoughts?

mdyring
perhaps it is cheap already and the IO issue is due to the leveldb thing, though
i think no-empty-blocks, which also behaves as block-on-demand is great for latency sensitive-ish stuff like dex (and makes more competitive to likes of hashgraph).. so would hate to not have it..

Zaki: think i will open an issue for it, as more of a question.. but i think it needs some thought. perhaps it can be worked around by having a minimum block time as well, in the no-empty-block case which will act as a batching mechanism..
personally I'd just prefer if block creation is cheap. :-)

Zaki
I don't have enough of a mental model of tm internals
I have observed tx batch behavior
batching
so I don't know exactly what is the constraints on that
If you send some quick sequence of txs to gaia-1, they get batched into block

mdyring
ok.. maybe it is already there then. i'll open the issue and then hopefully we can have a definitive answer.
but i'd guess just the time it takes to reach consensus means there is time to "batch"
so might not be something specifically implemented but just a side effect of delaying for consensus
```

**Comment by ebuchman** [comment]
Note that validators are expected to wait `timeout_commit` (default 1s) before starting the next block, regardless of transactions/no_empty_blocks settings. So the block time should not dip below 1s.  We can't really enforce this, but at least Cosmos will reward proposers for including more signatures, so they're encouraged to wait a bit before proposing their block to make sure they get all the signatures. If they're getting 100% of signatures in < 1s, well, then maybe we will have < 1s blocks, but that's a good problem to have with 100 validators on a WAN :D 

IO cost in general for a block should be quite low. Block headers max out around two-hundred bytes. Each vote is about 150 bytes, and a block includes ~1 vote for each validator (well, at least 2/3 of the voting power). So an empty block with 10 validators should be <2kB. From what folks have reported, we seem to be writing ~2MB/s. So that's 1000x amplification, which is obviously bad - the issue seems to be due to goleveldb compaction activity. We'll investigate if we can improve this by tweaking leveldb parameters.

I'm going to close this so we can focus conversation in https://github.com/cosmos/gaia/issues/111 with the info/logs there.

**Comment by ebuchman** [comment]
Oh wait. We're talking about disk IO during catchup. Well we sync about 100 blocks for second, so we should expect disk IO of about 200kB/s. We're seeing 2MB/s. So that's only 10x amplification from goleveldb, which seems much more reasonable!
