### ISSUE TITLE
Cannot recover from bonding too much ATOM

### ISSUE THREAD

**Issue by kidinamoto01** [cosmos/gaia#121]
Hello,

In my own testnet , I started four nodes each with power of 10. I tried to increase the power of one node to 50 and got the following errors:

`ERROR: Error starting proxy app connections: Error on replay: Commit failed for application: Error changing validator set: the change in voting power must be strictly less than 1/3`

The network totally crushed and cannot be recovered. 

Is there a way to avoid this kind of error?

Thanks.

**Comment by rigelrozanski** [comment]
hmm interesting - this error seems insane in a realistic network because if one party owned that many atoms that validator would effectively own the network and could double spend... not sure we should stall the network if this happens though (@ebuchman ?) 

And yes the way to avoid this error is to NOT send transactions which are greater than 1/3 of the total voting power! aka. if you start with 40 atoms bonded (4 validators * 10 atoms each) then no single validator can bond more than 5 atoms from this state (15 / 45 = 1/3) ........ easy solution is just have your genesis validators start with a larger number of atoms and work with far fewer atoms

**Comment by amrali** [comment]
```I[02-27|22:43:22.268] Executed block                               module=state height=2787 validTxs=1 invalidTxs=0
I[02-27|22:43:22.268] Updates to validators                        module=state updates="[{\"pub_key\":\"0198683F1418228F4D5FEEAFE98E77BEF9DF19D81B9794CC786D40B533D67DA21E\",\"power\":10002}]"
E[02-27|22:43:22.268] Error on ApplyBlock. Did the application crash? Please restart tendermint module=consensus err="Commit failed for application: Error changing validator set: the change in voting power must be strictly less than 1/3"
captured terminated, exiting...``````

We experienced this today on gaia-3003. I understand this is an extreme situation that is unlikely to happen on a production network. But perhaps an alternative solution to stalling the network is to try to prevent such situation with reasonability checks on the bonding transaction or have the network nodes recover gracefully by rejecting the bonding transaction.

**Comment by zhiqiang-bianjie** [comment]
@amrali ,I think the necessary preventive work is still needed, before binding and unbinding Atom, the best check. Can not because of a small probability event, leaving a fatal bug, do you think?

**Comment by ebuchman** [comment]
> ERROR: Error starting proxy app connections: Error on replay: Commit failed for application: Error changing validator set: the change in voting power must be strictly less than 1/3

This constraint was removed in Tendermint v0.16.0 because some applications have a real use case for more than 1/3 changing at once.

We should not allow it to happen in the Cosmos Hub though.

**Comment by amrali** [comment]
@ebuchman I'm glad that you agree, but wouldn't that necessitate adding back the constraint in Tendermint with the option to disable it? or perhaps it should be disabled by default and have Cosmos Hub code enable it.
