### ISSUE TITLE
DOCS: Deploy Testnet needs an update

### ISSUE THREAD

**Issue by nooomski** [cosmos/gaia#1244]
I was checking the broken links in the Check Markdown Link and found that [Deploy Your Own Gaia Testnet](https://github.com/cosmos/gaia/blob/main/docs/hub-tutorials/deploy-testnet.md) is heavily outdated as its still relying on the supporting code in the now missing "networks directory".

We can use this issue to discuss what we want to achieve with this article and hopefully provide a revamped article (or decide to remove it all-together).

**Comment by pankaj0812** [comment]
Hi @nooomski . I was trying to setup a MultiNode Local Automated testnetwork following the docs, and found an issue with the Makefile which relies on the networks/ directory, which currently has been moved to contrib/ in the main branch. 

In order to get the setup to work, we probably need to change `
	$(MAKE) -C networks/local` to 
`$(MAKE) -C contrib/testnets/local`. I have raised a PR for the same #1349. Please have a look.

**Comment by okwme** [comment]
as part of this we should move the other devnet documentation into this tutorial as a larger devnet tutorial.

similarly the migration tutorials should be moved to the mainnet repo.

**Comment by nooomski** [comment]
Closed by #1466
