### ISSUE TITLE
Config file should be ok having your own IP

### ISSUE THREAD

**Issue by sunnya97** [cosmos/gaia#127]
Everyone can have the same config.toml then and don't have to edit after committing to shared config.toml

**Comment by rigelrozanski** [comment]
Is this not a tm-core issue?
@ebuchman?

**Comment by krisrp** [comment]
I mentioned in the testnet launch the other day that it'd be tricky, as if you use DNS instead of an IP, tendermint has no way of knowing which address is yours.

Maybe there's an elegant solution, but personally I don't think it's a huge issue as testnet launches are infrequent, and some configuration is always going to be required.

**Comment by krisrp** [comment]
Thinking out loud here.
It might make sense to require that seeds use dns (like with bitcoin/etc) in config.toml, as IP's come and go over the years. It's not unreasonable for the 5-10 seeds used for bootstrapping to eventually drop offline or change IP. This could save having to update the config and allow seeds to use round-robin + failover (caching issues aside). No additional code needs to be written for it.

**Comment by nickray** [comment]
Due to P2P gossip you end up trying to connect to your own node anyway..

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1275
