### ISSUE TITLE
v6.0.3 release is using an older version of ibc-go

### ISSUE THREAD

**Issue by soareschen** [cosmos/gaia#1284]
## Summary of Bug

In v6.0.1 and v6.0.2, the version of `ibc-go ` has been updated to v2.0.3. However in gaia v6.0.3, the version of `ibc-go` has been reverted back to v2.0.0. This cause regression in bugs that have been fixed in ibc-go, such as https://github.com/cosmos/ibc-go/issues/601.

## Version

v6.0.3

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
yes we made `v6.0.1` and `v6.0.2` in the same day when we realized we hadn't bumped everything we could. However after releasing `v6.0.2` we found app-hash mismatch (#1280) and so made an emergency release of `v6.0.3` with the same features as `v6.0.0`. We are still working through trying to find the source of the non-determinism and will cut a safe `v6.0.4` with all relevant updates as soon as the issue is detected.
