### ISSUE TITLE
Non-determinism

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#1304]
## Summary of Bug

This is a reversion release that matches the v6.0.0 release. This is because an app-hash mismatch was detected when running v6.0.2 and it is expected that the problem is in v6.0.1 as well. Detection of the source of the nondeterminism is ongoing. In the meantime please use this release of v6.0.0. Please note that this release has binaries with a different check-sum than the v6.0.0 binaries because we used a docker image that uses go v1.17 instead of the docker image that was used to build the v6.0.0 release which used go v1.15.

## Origin

It isn't in Tendermint or Cosmos-sdk, I have upgraded too many chains for that to be the case.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
Thanks @faddat, we've arleady released a v6.0.3 that reverts the non-determinism and have located the source of the non-determinism as being present in the liquidity module v1.4.4. There is a new release of liquidity (v1.4.5) which is deterministic. They have begun properly releaseing with semver so that the breaking changes are in v1.5.0, we just haven't gotten around to releasing gaia v6.0.4 yet.
