### ISSUE TITLE
Can't get supply uatom amount with specific block height through curl request

### ISSUE THREAD

**Issue by yj0x0x** [cosmos/gaia#1370]
## Summary of Bug

curl -v -H "Content-type: application/json" -H "x-cosmos-block-height: 5201793"  http://127.0.0.1:1317/cosmos/bank/v1beta1/supply/uatom

Return 
```
{
    "amount": {
        "denom": "uatom",
        "amount": "0"
    }
}
```

## Version
v6.0.4

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by glnro** [comment]
Hi @yj0x0x, the issue is that you're trying to query a block at the [beginning of cosmoshub-4](https://github.com/cosmos/gaia/tree/main/docs/roadmap). Depending on the node you're querying, it may not have access to state at that height. If you'd like to use the publicly available api, you can find the supply at height `5201793` by running `curl -X GET "https://api.cosmos.network/cosmos/bank/v1beta1/supply/uatom" -H "accept: application/json" "x-cosmos-block-height: 5201793"`. See the [cosmos api docs](https://v1.cosmos.network/rpc/v0.41.4) for the corresponding version of gaia and the sdk for more info. 

I believe the response you're looking for is
```
{
  "amount": {
    "denom": "uatom",
    "amount": "291733611549391"
  }
}
```

**Comment by yj0x0x** [comment]
> Hi @yj0x0x, the issue is that you're trying to query a block at the [beginning of cosmoshub-4](https://github.com/cosmos/gaia/tree/main/docs/roadmap). Depending on the node you're querying, it may not have access to state at that height. If you'd like to use the publicly available api, you can find the supply at height `5201793` by running `curl -X GET "https://api.cosmos.network/cosmos/bank/v1beta1/supply/uatom" -H "accept: application/json" "x-cosmos-block-height: 5201793"`. See the [cosmos api docs](https://v1.cosmos.network/rpc/v0.41.4) for the corresponding version of gaia and the sdk for more info.
> 
> I believe the response you're looking for is
> 
> ```
> {
>   "amount": {
>     "denom": "uatom",
>     "amount": "291733611549391"
>   }
> }
> ```

hello. 
My node config is pruning `nothing`. 
Even though I can't get supply from rest api?

**Comment by glnro** [comment]
Hi @yj0x0x this depends on when your node started syncing. If it is a full archive node with all historical data since the beginning of `cosmoshub-4` then you would be able to query this. At this time a full [archive node](https://quicksync.io/networks/cosmos.html) is around ~`1.9TB` in size. If you synced any other way then this would be why your node doesn't have this information at that height.

**Comment by yj0x0x** [comment]
Thank you for the reply. 

I think supply API has error. 
In[ cosmoshub-4](https://github.com/cosmos/mainnet/blob/master/genesis.cosmoshub-4.json.gz) genesis file,  uatom issuance is -268335648775167	uatom then when I query like; 
```
curl -k -X GET "https://api.cosmos.network/cosmos/bank/v1beta1/supply/uatom" -H "accept: application/json" "x-cosmos-block-height: 5200791"
{
  "amount": {
    "denom": "uatom",
    "amount": "291954458310530"
  }
```

result is `291954458310530` utom. 

uatom issue amount is correct?

How all of sudden large amount of atom supply increase?

**Comment by yj0x0x** [comment]
and when I add `-H` to request result like below 
```
curl -k -X GET "https://api.cosmos.network/cosmos/bank/v1beta1/supply/uatom" -H "accept: application/json" -H "x-cosmos-block-height: 5200791"
{
  "amount": {
    "denom": "uatom",
    "amount": "0"
  }
}
```

Am I wrong something?

**Comment by glnro** [comment]
@yj0x0x I'll try to get back to you within 24 hours but if you need a more urgent response I suggest [joining the cosmos discord](https://discord.com/channels/669268347736686612/699634178173698108) for more timely support.

**Comment by yj0x0x** [comment]
@glnro Ping.

**Comment by okwme** [comment]
Hi @yj0x0x. you've made an interesting observation that the token supply increased a large amount between the genesis block of cosmoshub-4 and the query for the same height. However that is not the issue that you originally opened which I beleive as been addressed. To query the supply for a specific height, you need to have a copy of the blockchain that contains data from that height.

to get a copy of the chain with data from that height please download an archive snapshot from https://quicksync.io/networks/cosmos.html

thank you for your issue! if you'd like to discuss the token supply topic further please open a separate issue.
