### ISSUE TITLE
Integrate Bech32 addressing into Gaia

### ISSUE THREAD

**Issue by mmulji-ic** [cosmos/gaia#1712]
## Summary

Integrate the Bech32 addressing into the Gaia

## Proposal

- [ ] Import module from Osmosis repo in app.go
- [ ] Configure module manager
- [ ] Confirm it’s correct based on how the [osmosis chain](https://github.com/osmosis-labs/osmosis) includes it
- [ ] Add to e2e tests
- [ ] Add docs

See [bips](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) for more info.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
looks like ummee actually updated this code already to v0.46.

based on reduced work scope and recent conversation with osmisis on why they stopped supporting it (it's only useful on the cosmos hub actually) i think we should reconsider including into Rho.

the ummee version is here:  
https://github.com/umee-network/bech32-ibc

integrated here:  
https://github.com/umee-network/umee/blob/main/app/app.go

the original osmosis implementation has a similar e2e framework as us that we can re-use parts of to confirm the code was imported correctly.

valuable snippets follow:  
https://github.com/osmosis-labs/bech32-ibc/blob/165b8adbd1eaf689cb1794e20da6f78ce3490a33/test/relayer_bech32ibc_test.go#L126

@faddat is looking into adding it directly to gaia already.  IG team may still want to consider adding the e2e and the docs in order to include in Rho (would say only if we decide to include liquid staking in Rho after all).

**Comment by glnro** [comment]
@okwme if you're going to play this now then I think the expectation is if you implement the feature then docs and e2e are also part of the story/acceptance criteria.

**Comment by okwme** [comment]
#1768

**Comment by mpoke** [comment]
@mmulji-ic @glnro is this still relevant?

**Comment by glnro** [comment]
It was decided to put into a subsequent release...there's [an implementation in umee ](https://github.com/umee-network/bech32-ibc)I believe but I think if we decide to play this then we should implement it directly in gaia. I would recommend for v10 (also would have to spec out any requirements like a specific ibc version).

**Comment by mpoke** [comment]
We should first write an ADR first to document this change.
