### ISSUE TITLE
test: upgrade test

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1870]
## Summary
~~Add upgrade test in workflow for major release/rc-release during release process.
This test is triggered by a label "major_release", and is configured to upgrade from last major release to present version.~~

EDIT: create nightly build that can be passed to Hypha for testing version-specific features and simulating an upgrade from the current mainnet version

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by okwme** [comment]
- [x] fix the denom KV storage issue and overwrite with correct data
- [x] make issue on sdk about bank kv store being inconsistent between v045 and v0.46
- [x] convert script to use cosmovisor so that the panic will actually kill gaiad running and allow the upgrade to take place
- [ ] make a new script that uses recent theta testnet genesis instead of modified genesis from scratch
- [x] build last release as part of action CI and move to ./build/gaiad7 to run legacy node
- [x] figure out a way to read the output automatically to determine whether the upgrade succeeded or not
    - [x] check the liveness test logic

**Comment by MSalopek** [comment]
Closing as completed in [#2328](https://github.com/cosmos/gaia/issues/2328)

Please favor reopening [#2328](https://github.com/cosmos/gaia/issues/2328) in case additional work needs to be done or there is more information.

> EDIT: create nightly build that can be passed to Hypha for testing version-specific features and simulating an upgrade from the current mainnet version

Currently the relevant `release/*` branches and `main` are used.
