### ISSUE TITLE
Rest endpoints appear to have gone away

### ISSUE THREAD

**Issue by jtremback** [cosmos/gaia#2074]
## Summary of Bug

- Some change in some rest endpoints, for example /blocks/latest, has made them not work
- This would be a big issue for block explorers so we can’t release without addressing this
- The odd thing is that the SDK version bump is a minor bump from 45.9 to 45.11, and was just supposed to add some RS related code to prepare for the release of Gaia v9
- This needs to be summed up and presented to Marko or someone from the SDK team

**Comment by julienrbrt** [comment]
I have tried with simapp and these endpoints do work.

~~The only issue I can think about is https://github.com/cosmos/cosmos-sdk/issues/13695, but it gives another error.
The above issue is due to an issue in the way a chain load its config. This had popped up in a point released because we shadowed a variable (which we've reverted in v0.45.12).~~ EDIT: I don't see an error with your config loading, so I don't think it's that.

**Comment by ryujimin220** [comment]
We cannot provide services due to the same issue.

## Tested Port
- 1317 : not working
- 26657 : good
- 9090 grpc : good

## Environment
- OS : Ubuntu-2004-focal-64-minimal
- Gaia : v8.0.0 RC3
- Go : go1.19.5 linux/amd64

Both our archive and rpc nodes are facing this issue. 

I do agree that this version should have been blocked from releasing.

**Comment by yaruwangway** [comment]
tested with sdk 0.45.12 for v8:

the followings are there:
- block?height=_  
- validators?height=_&page=_&per_page=_

the following are still  missing:
- blocks/latest 
- validatorsets/latest
- node_info/synching

**Comment by jtremback** [comment]
@julienrbrt sorry for assuming this was a Cosmos-SDK thing when it was indeed in our app
