### ISSUE TITLE
Fullnode can't sync data anymore while someone is calling rest-api

### ISSUE THREAD

**Issue by congle-engineer** [cosmos/gaia#2415]
Hi all,

I'm a dev from Moonstake team. I'm running COSMOS fullnodes to provide data for Moonstake wallet. 

I have checked and found that when my colleague is calling rest-api to do some business from his side, the fullnode can't sync data anymore. I tried to change some configs, such as:
+ grpc_max_open_connections = 900
+ max_open_connections = 900
but it didn't help

What should I do for now to increase the number of concurrent requests that my fullnode can handle at a time?
Thank you in advance

**Comment by MSalopek** [comment]
Hey, thanks for opening the issue.

Would you be able to share which APIs seem problematic?

The problem is usually not with the number of connections, it's instead a problem with running expensive queries multiple times in short succession.

The solution mostly comes down to your business needs but try to employ some or all of these:
1. don't treat your full node the same you would a backend server
   -  the full node does more than just serve data from a DB
2. employ well understood engineering practices to protect problematic routes:
   - using caching
   - using rate limits
   - preventing access from the outside
3. use an indexer
   - removes load from your full node
   - great solution but can incurr an additional cost (running an extra db)
   - great for data that's expensive to calculate

Please check if indexing data is beneficial to your use case. There are open source indexers such as [bdjuno](https://github.com/forbole/bdjuno).

**Comment by MSalopek** [comment]
@congle-engineer 
Hey, I'm checking up on this issue.

Were you able to resolve your issue or learn anything from the previous comment?

**Comment by MSalopek** [comment]
Closing as there was more 3 months of inactivity.

Please tag me if you need to re-open.
