### ISSUE TITLE
Request to update roadmap

### ISSUE THREAD

**Issue by rootulp** [cosmos/gaia#2451]
https://github.com/cosmos/gaia/blob/8a522e98a2863205cf02fb97f8ad27d091670b9d/docs/roadmap/cosmos-hub-roadmap-2.0.md?plain=1#L46-L66

We're in Q2 2023 so I wonder if this section of the roadmap needs to be updated

**Comment by gjermundgaraba** [comment]
Yes, and will the hub go directly to 0.47 or use 0.46 first?

**Comment by mpoke** [comment]
> Yes, and will the hub go directly to 0.47 or use 0.46 first?

@gjermundgaraba Gaia will upgrade directly to 0.47. You can follow the work in this EPIC https://github.com/cosmos/gaia/issues/2413.

**Comment by jtremback** [comment]
@gjermundgaraba @rootulp - thanks for taking a look and leaving an issue.

In the past, this file contained about which SDK modules etc would be landing on the Hub, and when. This was almost always incorrect or outdated because it is hard to predict these things. Now it is kind of a vestige. You can follow along with our progress, thinking, and priorities at the blog on https://medium.com/@Cosmos_Hub. For example:

https://medium.com/@Cosmos_Hub/hub-engineering-update-first-consumer-chain-launch-ae680a3020bc
