### ISSUE TITLE
Reformat transaction flags in E2E tests

### ISSUE THREAD

**Issue by sainoe** [cosmos/gaia#2477]
## Summary

Many e2e tests tx calls are executed with inaccurate fee and gas-price flags which generally spend too much gas than required, e.g. see [execWithdrawReward](https://github.com/cosmos/gaia/blob/26dcfaedba559b8af42714c0971573ab108357c3/tests/e2e/e2e_exec_test.go#L571).

## Closing criteria
The e2e test tx calls must have their fee and gas-price flags normalized according to the local and network fee requirements ( i.e. config and global fee min-gas prices test setup).

## Type

Test Debt
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
In subsequent releases the globalfee module will be phased out and replaced with a feemarket.

I don't think this is a worthwhile effort if it's not done as part of a larger refactor or as part of a feature integration.

The e2e tests will be updated during feemarket integration, so this issue is no longer relevant since the work will be tracked elsewhere.
