### ISSUE TITLE
update docs after upgrading to cosmos-sdk v47 and ibc-go v7

### ISSUE THREAD

**Issue by glnro** [cosmos/gaia#2537]
# Problem

Upgrade documentation in case it goes out of date after upgrading to SDK v0.47, IBC v7 and CometBFT v37

```[tasklist]
#### SDK v0.47
- [x] Genutil module command changes (gentx, collect-gentx, add-genesis account)
- [x] Governance module API changes
- [x] Params module depreciation
- [x] denom owners deprecation
- [x] gov submit proposal instructions
- [x] antehandler for voting
- [x] check release notes for other highlights (especialy API changes)
```

# Problem details

**Comment by MSalopek** [comment]
Progress is on [feat/sdk-47-ibc-7](https://github.com/cosmos/gaia/tree/feat/sdk-47-ibc-7) branch.

This task was renamed to `[update docs after upgrading to cosmos-sdk v47 and ibc-go v7](https://github.com/cosmos/gaia/issues/2537)` since upgrading the tooling was mostly done on the feature branch above.
