### ISSUE TITLE
How to run the `light client`?

### ISSUE THREAD

**Issue by 99Kies** [cosmos/gaia#2621]
This blog(https://www.parity.io/blog/what-is-a-light-client/) explains what I need. I've seen light client in ibc(https://tutorials.cosmos.network/academy/3-ibc/5-light-client-dev.html) and tendermint's documentation(https://docs.tendermint.com/v0.34/tendermint-core/light-client.html), but ibc describes it to me as an on-chain light client, So I was curious if the `light client` in ibc and the `light client` mentioned in tendermint were the same thing.

And finally, what should I do if I want to run the light client node I need.

**Comment by MSalopek** [comment]
Thanks for opening the issue!

The [blog post](https://www.parity.io/blog/what-is-a-light-client/) you sent explains the basics of a light node and how it's used on Ethereum.

The concepts translate well onto cosmos-sdk/cometbft based blockchains but you are missing some important parts.

In the context of IBC the client used is of type `07-tendermint` which is embedded in the state of a blockchain. You don't need to "run it", it's not a separate binary.

There is a [`06-solomachine` light client](https://tutorials.cosmos.network/academy/3-ibc/6-solomachine.html) that might be closer to what you want. This light client can be run as a separate process (there's a binary you can run on a machine) and will function the same way as the `07-tendermint` light client. You can read about it [here](https://ibc.cosmos.network/v7.1.0/ibc/light-clients/solomachine/solomachine.html). Since every `cosmos-sdk` chain is a bit different, it seems to me that you will need to create your own implementation of `solomachine` light client to be able to run it.

Here is an example (probably outdated) where a team implemented a `solomachine` light client in rust:
- https://medium.com/the-interchain-foundation/ibc-beyond-light-clients-solo-machine-5af93618ef63
- https://github.com/crypto-com/ibc-solo-machine

Pasting in the IBC specs for reference:
- https://github.com/cosmos/ibc/tree/main/spec/client/ics-006-solo-machine-client
- https://github.com/cosmos/ibc/tree/main/spec/client/ics-007-tendermint-client

**Comment by MSalopek** [comment]
Closing this issue since no discussion is happening and the requested information was provided.

Feel free to tag me if you need more information so I can reopen the issue.
