### ISSUE TITLE
Can't create another wallet address in Keplr wallet using Multisig

### ISSUE THREAD

**Issue by marius987654** [cosmos/gaia#2805]
## Summary of Bug

I was trying to create a second account in Keplr mapped to my Ledger device. I encountered the error message "no compatible device found" although Ledger was connected and Cosmos app was installed
## Version

 release/v13.x-8482ac1b3fafcbebd01dfde347b3fa3ec35bfce1

## Steps to Reproduce

 In the Keplr wallet extension, select add wallet, connect hardware wallet, turn on ledger, open Cosmos app on ledger, select, connect ledger, name the wallet, select connect to cosmos, advanced settings, derivation path do ( 2 , 0 , 0), next, next, error.
![image](https://github.com/cosmos/gaia/assets/121251275/e679decb-7011-4b62-9030-45afdc30ff3a)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
- [ ] Is a spike necessary to map out how the issue should be approached?

**Comment by MSalopek** [comment]
Hey, thank you for opening this issue.

I am sorry that you are facing issues during your wallet creation.
Unfortunately, this is not a gaia issue - you are trying to add a wallet to the Keplr browser extension and you are not interacting with the gaia binary in any way. The binary you listed and have on your computer does not interact with Keplr in the wallet registration step.

Possible solution is trying the alternative USB connection method listed on the onboarding screen in Keplr (during the wallet registration).
Besides that, please check that you can connect your device to the Ledger Live application and your firmware is up to date. You can install it using the link below:
* https://support.ledger.com/hc/en-us/articles/4404389606417-Download-and-install-Ledger-Live?docs=true

These links may help debug connecting Ledger to Keplr:
* https://support.ledger.com/hc/en-us/articles/4405542078353-Windows-doesn-t-recognize-my-Ledger-device?support=true
* https://medium.com/@paulsjones/ledger-live-not-recognizing-my-device-what-to-do-10b6db98184a
* https://support.ledger.com/hc/en-us/articles/115005165269-Fix-USB-connection-issues-with-Ledger-Live?support=true

Since the title does not match the contents of the issue description, do you mind elaborating on the quote below? I am asking because adding a wallet to Keplr is not related to multisig.

> Can't create another wallet address in Keplr wallet using Multisig

Please, do let us know if you manage to resolve your issue in the meantime or have additional information.

**Comment by marius987654** [comment]
I think the error was on my side. I entered the params incorrectly for creating a new account on my Ledger. The multisig point was related to the purpose why I am creating a new account (am testing a multisig UI developed by Keplr for the Foundation).
