### ISSUE TITLE
Can bonded validators be slashed for infractions more than an unbonding period in the past?

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/gaia#29]
See discussion from: https://github.com/cosmos/cosmos-sdk/issues/1022

**Comment by jackzampolin** [comment]
Related: https://github.com/cosmos/cosmos-sdk/issues/1378

**Comment by tmckenzie51** [comment]
Hi @jackzampolin ! Thank you for opening up this discussion here. We've been behind and apologize for such. Would you mind confirming whether this is still a discussion that we'd like to keep open in this issue here? We'll close this issue in 1 week if we don't hear back from you before then. Of course, if necessary we can always reopen this issue. 
Thanks for your help,
Cosmos Hub Team

**Comment by nooomski** [comment]
This depends on the `MaxEvidenceAge` set in the `x/evidence` module. Evidence won't be reported to the application if it's outside this evidence age.
