### ISSUE TITLE
Rename Repo to `cosmos-hub`

### ISSUE THREAD

**Issue by mappum** [cosmos/gaia#3]
Just filing an issue so we remember to get to this when convenient. Since we aren't creating a separate Gaia network anymore, this repo will become the Cosmos Hub.

**Comment by rigelrozanski** [comment]
Okay yes, keeping this for git history rn, may end up doing some fancy git
stuff and adding into the sdk, then generating a new repo for the hub

On Aug 18, 2017 5:30 PM, "Matt Bell" <notifications@github.com> wrote:

Just filing an issue so we remember to get to this when convenient. Since
we aren't creating a separate Gaia network anymore, this repo will become
the Cosmos Hub.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cosmos/gaia/issues/3>, or mute the thread

**Comment by rigelrozanski** [comment]
@ebuchman I think we should rename as soon as staking is merged into the new SDK - all that will be left at that point is the HUB

**Comment by zramsay** [comment]
this repo is going into cosmos-sdk, isn't it?
