### ISSUE TITLE
Denom handling in gaiacli

### ISSUE THREAD

**Issue by zmanian** [cosmos/gaia#300]
Currently users of gaia need to enter amounts in uatom and multiply ATOM denominated transactions in `uatom`.

The cosmos SDK merged https://github.com/cosmos/cosmos-sdk/pull/3747 last year but these features never made it into gaia.

This would be done. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Agree, the REST and CLI clients should accept any valid registered denom unit and via the PR you referenced, covert it to `uatom` prior to signing.

**Comment by okwme** [comment]
I can't find an example in simapp where the denom type utilities are utilized in order to implement into gaia. Shouldn't this be implemented at the SDK level in bank and be automatically incorporated into gaia? If it needs to be set explicitly in the gaia cmd would love a link to somewhere as a reference for how to use 🙏

**Comment by zmanian** [comment]
This might even have been fixed upstream. Let's close it.
