### ISSUE TITLE
[Question] The transaction failed to be uploaded to the chain. Unable to update fee market state: block utilization of 30035129 cannot exceed max block utilization of 30000000

### ISSUE THREAD

**Issue by zelonH** [cosmos/gaia#3236]
The transaction failed to be uploaded to the chain. Can you tell me the reason? Unable to update fee market state: block utilization of 30035129 cannot exceed max block utilization of 30000000, https://atomscan.com/transactions/A1BAEB15ECBED9E8C6EB667F8C01112FEA9F110C84E7D298558F6A4F30F57686

How is the handling fee of Cosmos calculated? 
```
 "fee" : {
      "amount" : [ 
        {
          "amount" : "1000",
          "denom" : "uatom"
         }
       ],
      "gas" : "200000"
    },
```

**Comment by MSalopek** [comment]
You can safely re-try the transaction, the hub is using the [feemarket module ](https://github.com/skip-mev/feemarket/tree/main/x/feemarket) with EIP-1559 semantics - this is it in action.

The transaction failed because the block gas limit is `30 000 000`. The block was full so your Tx was not included.

Whenever the block gas counter exceeds `15 000 000` the gas price will increase. You can check the current gas prices via:
```
gaiad q feemarket gas-price uatom --node "https://cosmos-rpc.polkachu.com:443" -o json
```

Please let us know if you've managed to perform the operation.

@hanzhenlong1314

**Comment by MSalopek** [comment]
This issue was addressed in proposal:
* https://www.mintscan.io/cosmos/proposals/970
* https://forum.cosmos.network/t/proposal-draft-update-feemarket-max-block-utilization-to-75m-gas/14227

New gas limit is `75M`.

Closing as completed.
