### ISSUE TITLE
Bump wasmd to the latest version (0.53)

### ISSUE THREAD

**Issue by mpoke** [cosmos/gaia#3287]
## Problem

The version of wasmd needs to be updated before cutting v20.

**Comment by MSalopek** [comment]
More context:
Aside from doing a version bump, build systems need to be updated.

This includes:
* docker images (e2e and node)
* goreleaser
* tests

The build system produces statically linked binaries because of libwasm deps.
Goreleaser uses a docker image for cross-compliation that needs to be updated and correct build flags need to be used.
