### ISSUE TITLE
Add more info

### ISSUE THREAD

**Issue by wimel** [cosmos/gaia#366]
## Summary

Can we add the discord channels to the info in [join mainnet](https://github.com/cosmos/gaia/blob/master/docs/gaia-tutorials/join-mainnet.md#add-seed-nodes) docs?

## Problem Definition
Recently we are using Discord rather than Riot.
The people can find all the chats/channels to organise in one document.

## Proposal

Add some Discord channels:

- [Introduce yourself](https://discordapp.com/channels/669268347736686612/669268347736686615)

- [General](https://discordapp.com/channels/669268347736686612/669275164999155742)

- [Announcements](https://discordapp.com/channels/669268347736686612/669488112807706625)

- [Validators](https://discordapp.com/channels/669268347736686612/669274895041036349)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
I like this idea, but would take it a step further and recommend that links to social resources be put directly on Readme.md

I like to think of a project's Readme.md on Github/Gitlab as the "landing page" to the project, and all of the *key* info should be there.  I think that chats certainly qualify as key since they let users get in touch with the community and ask questions directly.

**Comment by faddat** [comment]
Adding this to #383 

Probably better to link to the discord server itself instead of different channels.
