### ISSUE TITLE
upgrade 3.0 need help for protobuf

### ISSUE THREAD

**Issue by ghost** [cosmos/gaia#532]
i am wallet developer, i see cosmos 3.0 is release, change to protobuf
is transaction change version?
will I need update our app to support new version?

**Comment by tac0turtle** [comment]
Some transactions have changed but for many you are still able to use amino. If you are using javascript there is a library that is up to date for the new version (https://github.com/cosmos/cosmjs). It is recommended to upgrade to protobuf sooner rather than later but the deprecation of amino encoding is still a long way out.
