### ISSUE TITLE
Working relayers in Go, Rust, JS

### ISSUE THREAD

**Issue by ebuchman** [cosmos/gaia#576]
Initial Stargate compatible relayers are available in [Go](https://github.com/cosmos/relayer) and in [Rust](https://github.com/informalsystems/ibc-rs).

They still need a lot of work.

There is a tracking issue for relayers in [CosmJS](https://github.com/cosmos/cosmjs/issues/500).

Todo:
- [ ] Document feature sets for these relayers in this repo
- [ ] Document / link to their high level roadmaps
- [ ] Detail/Align on necessary upcoming features for them

**Comment by ebuchman** [comment]
Copied over from output of recent relayer call:

**Functionalities needed**
- Minimal set of queries
  - Clients, Connections, channels
  - Chain identifiers
  - Token source (i.e timeline/history of transfers for a token)
- Minimal set of transactions
  - Client creation and updates
  - Connection and channel handshakes
  - IBC transfers
- Modularity to support for different light clients other than Tendermint
- Solo machine support
- Network topology discovery
  - API for Map of Zone-like services
- Relay strategies
  - Which token do I choose to relay?
  - Through which route?
    - The cheapest (fees)?
    - The shortest route?
    - Most security?
    - The one that unwraps the token?
  - Do we leave these choices up to the user or will the relayer provide abstractions for this?
- UX abstractions for clients (wallet exchanges)
  - ICS20 token voucher representations
    - ibcATOM
- Subscription to Interchain Events:
  - Jelena: "track" tokens after they’ve passed through IBC so that you can get an accurate understanding of value transfer b/w chains

**Comment by colin-axner** [comment]
In the very short term, I'd like to see any interested party such as exchange/wallets/services commenting on how they plan to approach this issue, what tools they are using, what scripts they are using, do they intend to maintain a on-chain client, which channels are they going to hardcode and relay packet for, what chains do folks want to connect to, what features do they need from a relayer, what features do they want, etc

I think there is very little visibility in who is doing what for Stargate (or at least from my point of view). IBC is about interoperability so we should be coalescing around communication rather than DIY (as this issue is trying to do)

Is there somewhere, maybe in this repo, we can document recommended client/connection/channel identifiers once Staragate is live.

**Comment by okwme** [comment]
cc @zramsay

**Comment by tac0turtle** [comment]
we got relayers
