### ISSUE TITLE
validator set is nil in genesis and still empty after InitChain

### ISSUE THREAD

**Issue by yingjun-wu** [cosmos/gaia#673]
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
How to solve this mistake？

**Comment by tac0turtle** [comment]
do you have the correct Genesis file?

**Comment by cdkj** [comment]
You should focus on the config file **genesis.json**. The problems happens when you first execute **\<appd start\>**

When you execute **\<appd start\>** for the first time, **initchainer** will be executed and **genesis.json** will be used. What **initchainer** does is just read your **genesis.json** and transform it into **GenesisState** defined in **genesis.go**.

So before executing **\<appd start\>**, you need to prepare **genesis.json**.
It is not enough just to execute **\<appd init\>**. At this time, validators are not defined in **genesis.json**.

After init, you need to use the **\<appd keys\>** command to generate a secret key for the account you want to create, this is neccesary for create an account.

Based on the secret key you generated, you need to use **\<appd add-genesis-account\>** to register an account in genesis.json, an account is neccesary for create validator.

Based on your registered account, you need to use **\<appd gentx\>** to generate a genesis transaction. The content is to create a validator. Actually, what this command do is create a msg: **MsgCreateValidator**, and this message is written into a genesis transaction file in the path you specify.

Based on the genesis transaction file, you need to use **<\appd collect-gentxs\>** to write these genesis transactions into **genesis.json**.

Now, you can execute **\<appd start\>**.

After you understand these processes, solving your problems should no longer be difficult. Use the **--help** flag to learn how to use the above commands. If you are familiar with cosmos-sdk, you can also write your own program to customize your commands, so that creating a validator becomes less troublesome.

**Comment by okwme** [comment]
This issue is for a previous version of gaia. Please check updated [docs](https://hub.cosmos.network) to confirm you're following steps correctly. Going to close this issue, please re-open if you're still having issues
