### ISSUE TITLE
api /cosmos/staking/v1beta1/validators/%s/delegations is slow and high cpu usage

### ISSUE THREAD

**Issue by ghost** [cosmos/gaia#735]
gaiad v4.0.5

I need a api to get validators delegations address number.
i loop alll validators,get delegations address number,but the api is too slow, every call use 20 second
```log
 Served RPC HTTP response duration=22820 method=GET module=api-server remoteAddr= status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/cosmos/staking/v1beta1/validators/cosmosvaloper1x88j7vp2xnw3zec8ur3g4waxycyz7m0mahdv3p/delegations","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
```
and the block update will slow becase cpu competition, but process cpu use is only limit to 200%

**Comment by ghost** [comment]
IRIS api is faster than ATOM

**Comment by faddat** [comment]
@jingniao -- probably because the IRIS API will return less when making that call, because there's less state in the chain. 

Kind of related to 

#704

**Comment by faddat** [comment]
Likely also related to:

https://github.com/tendermint/tendermint/issues/6048

**Comment by mohammedpatla** [comment]
Bump, we are trying to use this, but this is still a issue to.

On our node we see high CPU usage with the latest binary 5.0.8. Even with high cpu usage it does not return values. 

We don't see this issue on Secret Network though. So I Think this was fixed in the sdk?

**Comment by tac0turtle** [comment]
Hey, this will be an issue for the sdk. In gaia we just use the staking module. There are a few teams complaining about this

From the sdks side of things this is a known issue, it is because of how iavl is designed and how we store the data on disk. There is a team working on this. 

Ill close this issue for now, but would be good to open one in the sdk for tracking purposes.
