### ISSUE TITLE
Fortio RPC response time testing

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#801]
## Summary

Fortio can be used to automatically test response times for each change made to Gaia. 

## Problem Definition

Currently, there isn't any formal testing done on Gaia, against live networks. Some RPCs are slower than others. 

## Proposal

Create a github action that kicks up a node with presynced state and the latest code.  The node connects to the actual live network.  Fortio runs against every endpoint.  Reports are captured.  We do this for every commit, on every branch.  

We monitor the rest of the node, and capture that, too.  This way, we know that block height is still advancing correctly, even under heavy load.  The correct setup will allow us to test and verify everything in a real-world way,. 

It'll require a 

https://github.com/actions/runner

to be set up.  

Reports will look like this as text:

https://raw.githubusercontent.com/istio/istio/release-1.0/mixer/test/perf/bench.baseline

But they can also be visually rendered.  This should help with the increase in traffic that happens when the DEX launches. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MSalopek** [comment]
> But they can also be visually rendered. This should help with the increase in traffic that happens when the DEX launches.

The comment seems to be from the Gravity days but that project did not live long.

While this seems like a valuable idea, most of the testing should be concerned about gaia functionality and stability.

The value gain here is not clear. Most of the current performance issues happen due to cosmos-sdk internals (data structures, data indexing etc) and cannot be addressed on gaia directly.

Let's close this issue for now. If there is community interest in developing this, we should re-open.
