### ISSUE TITLE
deployment: have scripts that help deploy multi-node testnets

### ISSUE THREAD

**Issue by ying2025** [cosmos/gaia#82]
how to deploy Multi-node in my Testnet , not by docker and AWS ? like deploy Single-node

**Comment by lhfbc** [comment]
Long time no answers...

**Comment by tac0turtle** [comment]
Hey if you would like to deploy a multi-node testnet you will have to manually link the nodes. We do not have tool that does this automatically, yet. Many validators have open-sourced their configurations and scripts to help with this. 

There is this tool: https://github.com/informalsystems/testnets/ that deploys tendermint but you could modify it to deploy instances of gaia.

I renamed the issue so we can track and hopefully provide something in the near future

**Comment by yaruwangway** [comment]
Hi @ying2025 ,
Thanks for open this issue! We've been behind on many reviews and apologize for such. 
Here is a bit more info if you are looking for scripts that help setup multi-nodes for testnet.
https://github.com/informalsystems/ibc-rs/tree/master/scripts/gm


Please let us know whether you have further questions regarding to this issue. Otherwise, we'll close this issue in 1 week if we don't hear back from you before then. If the issue persists we can always re-open.
Thanks for your help,
Cosmos Hub Team
