### ISSUE TITLE
Peer node setup

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/gaia#832]
Hi,
I am running private node in gaia. 
How to connect peer node in gaia network?
How to find seed node and persistant_peers id in gaia? 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by toschdev** [comment]
How to connect to a peer node. When mentioning that you run a private node, I assume that you host all the `peers` yourself in this case, right?

To connect to a peer, you need the peers ID, IP and Port it uses.
Find the ID of your node with running:

`gaiad tendermint show-node-id`

You need to combine the output with your IP and Port. So the final string will look like

`d72b3011ed46d783e369fdf8ae2055b99a1e5074@173.249.50.25:26656` (an example taken from https://github.com/cosmos/mainnet)

When you want to connect to the node from another machine, make sure to add the string 👆 to the `persistent_peers` in your `~/.gaia/config/config.toml` file

```
# Comma separated list of nodes to keep persistent connections to
persistent_peers = ""
```


You can setup a seed node with the following setting in your `~/.gaia/config/config.toml` file at the following setting:
 
 ```
 # Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false
```

Toggle to `true` if you want to create a `seed node`. If you have setup a seed node, you can use the `seeds` parameter in the `~/.gaia/config/config.toml` file instead of the `persistent_peers`

```
# Comma separated list of seed nodes to connect to
seeds = ""
```
