### ISSUE TITLE
Use 'file' as the default keyring on the headless Linux systems

### ISSUE THREAD

**Issue by pakuula** [cosmos/gaia#870]
## Summary

`gaiad` uses 'os' as the default keyring. In Linux 'os' connects to `gnome-keyring` that has issues with headless operations. Those issues prevent `gaiad keys add` with the default keyring from working.

## Problem Definition

The test case:
```
$ git clone https://github.com/cosmos/gaia
...
$ cd gaia
$ make build-linux
...
$ ./build/gaiad keys add test
Error: No such interface 'org.freedesktop.DBus.Properties' on object at path /
```

The reason for this error is how `gnome-keyring` works. 

When `gaiad` connect to `org.freedesktop.secrets` service and queries the list of available connections. If there is no collection named `gaia` then `gaiad` issues a call `CreateCollection`. Here is where the headless service fails. The service doesn't create the collection, instead it returns a [`Prompt` object that the application should invoke](https://specifications.freedesktop.org/secret-service/latest/ch09.html). The purpose of that `Prompt` is to ask the used to create the password for the new collection.

`gaiad` (actually, `go-libsecret` implementation that `gaiad` uses) invokes the method `Prompt` and it fails since there is no instance of 'org.gnome.keyring.SystemPrompter' object in the headless system. `gnome-keyring` returns '/' in the callback `org.freedesktop.Secret.Prompt.Completed` to demonstrate that `CreateCollection` failed. `go-libsecret` ignores this and proceeds with '/' as the object path. It tries to get `Locked` property of that object and receives the exception `No such interface 'org.freedesktop.DBus.Properties' on object at path /`. The error is misleading, the actual cause is the intention of `gnome-keyring` to interact with the end user.

Forwarding X over doesn't help. `gnome-keyring` ignores remote DISPLAY and tries to open the prompt at the screen where GNOME shell runs. Since there is no active GNOME session, the call to the prompt fails. `gnome-keyring` is usable as the keyring backend only for those users who have active GDM session, i.e. locally logged to the system through keyboard and mouse attached to the system. No remote login. 

Attached to this issue:
- the dbus monitor log of interactions between `gaiad` and `gnome-keyring` [gaiad-dbus.log](https://github.com/cosmos/gaia/files/6597849/gaiad-dbus.log)
- the screenshot of the password prompt on the headed system.
![1](https://user-images.githubusercontent.com/42604056/120790323-c577c500-c56d-11eb-94c6-33ec745f812f.png)

## Proposal

Using `gnome-keyring` in headless Linux systems makes `gaia` key management impossible. Choose `file`  as the default keyring for Linux systems.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tac0turtle** [comment]
Hey, thanks for opening this issue. @alessio may have some insight into this as he is our main linux wizard. 

We should keep keyring by default as the majority of people aren't the best in handling keys, they should be explicit about not using the filesystem

**Comment by alessio** [comment]
Thanks for filing this bug and contributing to making Cosmos SDK better (and thanks @marbar3778 for bringing this up to my attention).

Linux headless environments don't provide all required dependencies required by a fully working Freedesktop environment, thus GNOME Keyring does not work properly; this is a very well known limitation. On the other hand, the majority of developers and users working with Cosmos SDK on Linux tend to use systems that come with full-fledged GNOME or KDE installs - that's why we chose `libsecret` as the Cosmos SDK's keyring defaults, which provides them with a convenient and secure mechanism to secure their keys.

I am not opinionated at all about whether we should change the defaults. I'd leave this up for the community to decide.

Note: the `file` backend would prompt the users for their password _each and every time_ they access the keyring. This should be taken into account when assessing the UX impact of such a decision.

**Comment by okwme** [comment]
a good point is that the gaia docs are quite light on keyring backend information and this could be addressed there: 
https://hub.cosmos.network/main/resources/gaiad.html

**Comment by alessio** [comment]
The backend documentation is available here: https://docs.cosmos.network/v0.42/run-node/keyring.html#available-backends-for-the-keyring

**Comment by mmulji-ic** [comment]
@nooomski could you take a look and advise.

**Comment by nooomski** [comment]
Well first of all, this is a SDK issue, not a Gaia issue if I understand correctly.

I'm not an expert here, but it sounds to me the consensus is that:
- The impact is minimal as the the majority of users don't experience this
- Changing to `file` as default would make UX much worse for majority of users
- We should keep the default keyring as `os` unless we have stronger reasons not to

So, it sounds to me that we should:
1. Make sure we show a correct error with a note about the workaround using `file` (needs an issue on the SDK)
2. Update the [SDK documentation](https://docs.cosmos.network/v0.42/run-node/keyring.html#available-backends-for-the-keyring) with a small note about this possible issue
3. Add a link to the SDK docs in the [Gaia documentation](https://hub.cosmos.network/main/resources/gaiad.html) regarding keyring backend details (in order to avoid duplicating content)

If that sounds good, I'm happy to do all three of those actionables.

**Comment by pakuula** [comment]
@nooomski 
I'd say this is Gaia issue since the application decides which backend to use. But if the documentation tells about issues with `os` backend in headless environment and suggests using `file` backend, it is fine for me.

**Comment by nooomski** [comment]
It's a Gaia issue only in that it trickled down from the SDK. Other chains using the SDK will have the same issue as the default keyring is set on the SDK level iirc. Imo, error should be fixed on SDK side and go to Gaia when we integrate the next update. Docs should be updated on SDK side and linked to in the Gaia docs.

@marbar3778 does that sound good to you? If so I'll create an issue on the SDK and get started on docs.

**Comment by nooomski** [comment]
Closing this issue in favor of [fixing the error](https://github.com/cosmos/cosmos-sdk/issues/11850) on the SDK and having better docs in #1446
