### ISSUE TITLE
Add governance public key to spec

### ISSUE THREAD

**Issue by rigelrozanski** [cosmos/gaia#88]
https://github.com/cosmos/gaia/issues/63#issuecomment-350223466

**Comment by adrianbrink** [comment]
A validator should be able to declare a separate pubkey address that is allowed to vote in governance. This way validators are able to use a key for voting that holds no money nor validation power. Validators should be able to update that voting key as often as they would like. During a voting period only the latest vote for any given validator should count (so that even a compromised voting key doesn't matter).

Having a separate voting key will make it way easier to participate in governance. It might become harder to manage all the separate keys though, even though it could just default to the same key.

**Comment by rigelrozanski** [comment]
Added to spec
