### ISSUE TITLE
add seed nodes to binary

### ISSUE THREAD

**Issue by okwme** [cosmos/gaia#943]
## Summary

This is an issue to discuss following the example of Osmosis including peer nodes in the binary:
https://github.com/osmosis-labs/osmosis/pull/416/files#r691154309

## Problem Definition
Finding seed nodes is difficult and often tracked outside of the binary. The list changes over time and can be difficult to keep updated or keep track of.

## Proposal

Include a set of reliable seed nodes run by the ICF and other trusted validators as default seednodes for the gaia binary. Make regular patch releases to keep it updated as need be. Ensure that users can overwrite the default seed nodes set in the binary.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by okwme** [comment]
@marbar3778 said he's working on a heft seed node but i'd also be curious to hear @alexanderbez 's opinion on the endeavor.

**Comment by okwme** [comment]
also does this provide a solution for setting default values to config.toml and app.toml?
https://github.com/cosmos/cosmos-sdk/issues/9727

**Comment by alexanderbez** [comment]
Here is how I feel about peers and seeds.

The project's core team should have multiple reliable peers on infrastructure they run and maintain. I'm talking nodes that allow hundreds of inbound and outbound connections. They should then list these peers in the main README.md of the project's repo as a single source of truth (or some other easily accessible doc, e.g. their website).

The main reason most people have to "hunt" for peers is because no single team I've seen so far has put forth any significant effort into running reliable and dedicated infra for their project, e.g. 4-5 beefy nodes with 500+ I/O connections. Simply listing these nodes on their page would solve many issues. If these nodes get filled up, launch more.

I also like the idea of the Osmosis PR, but as someone pointed out, the seeds and/or peers can change (unless they are ran by the project's team and sit behind static hostnames, not IPs). But even if they do this, they might as well just do what I described above and not hard-code anything in configuration.

**Comment by jackzampolin** [comment]
Strong agree here.

**Comment by faddat** [comment]
I think they should be baked in the way that bitcoins are and that we should probably just download Genesis in the binary as well and then do a sha 256 sum on it.

Boom, zero hunting.

By the way, I looked into doing this with IPFS and added too many dependencies and was not stable but you can have a look at the little library that I made:

GitHub.com/notional-labs/get

By the way due to mysteries I do not understand, it will work on your computer but it does not work in CI. Anyhow, because of all those complications it's probably best to just do it in the binary with the HTTP library or some wrapper of that, so that In the binary what we specify is the URL for Genesis, which should refer to an IPFS CID, (download over http) and then we sha256 sum it.

**Comment by faddat** [comment]
I can put up a tender seed instance for Gaia the same way that I did for Osmosis.

**Comment by alexanderbez** [comment]
> I think they should be baked in the way that bitcoins are and that we should probably just download Genesis in the binary as well and then do a sha 256 sum on it.

There are various pros and cons to this approach. Personally, I don't think hard-coding seeds or the genesis file is a safe approach. Ultimately, the gaia team will have to decide.

**Comment by faddat** [comment]
I run several hefty gaia instances.

That's what she state syncs from.

https://github.com/faddat/gaia/runs/3502709806?check_suite_focus=true#step:7:7524

Yep, they take 500 incoming connections each, wouldn't have it any other way.

...but with state sync I'll soon be able to have a dozen gaia instances for state syncing from-- and they'll run in Akash, of course.

**Comment by faddat** [comment]
@alexanderbez 

Mind sharing your thoughts as to why not safe?

I shall begin with an awful cop-out:

Ethereum and BTC do it

....

Really though I'd like to hear your mind

**Comment by alexanderbez** [comment]
haha fair enough, I don't have super strong objections to this. I just think it can just be more error prone in certain contexts. In any case, feel free to open a PR if you haven't already.

**Comment by faddat** [comment]
cool, I think that my PR was closed, and likely for good reason, but I'll open er up again post vega.  There is likely a much cleaner way to do what I was trying to do.

**Comment by okwme** [comment]
hard coded seednodes will get full address books quickly if they are hit repeatedly. I think there is a change to how this works coming in Tendermint. Going to close and let @faddat re-open if/when it becomes relevant again.

**Comment by faddat** [comment]
Seed nodes dispatch peers then break off.
