### ISSUE TITLE
Fee related issue

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/gaia#953]
Hi everyone,
How to check miner reward in cosmos gaia?
And In which account transaction fee can be credited?

**Comment by yaruwangway** [comment]
Hi, gaia uses Proof-of-Stake here. 
validators get reward by validating blocks, delegators who delegate to them can  also get part of the validators' rewards.
For more details about reward, please refer
https://docs.cosmos.network/master/modules/distribution/#distribution
https://docs.cosmos.network/master/modules/distribution/03_begin_block.html#reward-to-the-validators
the params mentioned in the link, you can check by command `gaiad q distribution params`
check a validator's commission: `gaiad q distribution commission [validator]` 
check a delegator's reward from delegating to validators: `gaiad q distribution rewards [address]`

please let me know if you have further questions, otherwise I will close this issue. @osiz-blockchainapp
